=== anweisen/DyCloud/module-config-schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema",
	"$id": "https://raw.githubusercontent.com/anweisen/MinecraftCloud/master/module-config-schema.json",
	"title": "MinecraftCloud Module Configuration",
	"description": "Configuration of a MinecraftCloud module",
	"type": "object",
	"required": [ "name", "version", "author", "main" ],
	"properties": {
		"name": {
			"type": "string",
			"description": "The name of this module"
		},
		"version": {
			"type": "string",
			"description": "The current version of this module. Example: 1.2.7",
			"pattern": "^(?:(\\d+)\\.)?(?:(\\d+)\\.)?(\\d+)$"
		},
		"author": {
			"type": "string",
			"description": "The version of this module"
		},
		"main": {
			"type": "string",
			"description": "The main class name of this module, must extend CloudModule"
		},

		"description": {
			"type": "string",
			"description": "A short, human readable description of what this module does"
		},
		"website": {
			"type": "string",
			"description": "A url of the website of this module"
		},
		"depends": {
			"type": "array",
			"description": "A list with modules names which have to be loaded before this"
		},
		"environment": {
			"enum": [ "ALL", "MASTER", "NODE", "NONE" ],
			"default": "ALL",
			"description": "The environment on which the module should be run"
		},
		"copy": {
			"enum": [ "ALL", "PROXY", "SERVER", "NONE" ],
			"default": "NONE",
			"description": "The type of the service the module should be copied to as plugin"
		}
	}
}

=== anweisen/DyCloud/modules/bridge/src/main/resources/module.json
{
	"name": "Cloud-Bridge",
	"author": "anweisen",
	"version": "1.0",
	"main": "net.anweisen.cloud.modules.bridge.CloudBridgeModule",
	"website": "https://github.com/anweisen/DyCloud",
	"description": "Runtime module to enable the use of player management possible",
	"environment": "NONE",
	"copy": "ALL"
}

=== anweisen/DyCloud/modules/cloudflare/src/main/resources/module.json
{
	"name": "Cloud-Cloudflare",
	"author": "anweisen",
	"version": "1.0",
	"main": "net.anweisen.cloud.modules.cloudflare.CloudCloudflareModule",
	"website": "https://github.com/anweisen/DyCloud",
	"description": "Runtime module to enable the use of a multiproxy setup using round-robin dns load balancing",
	"environment": "MASTER"
}

=== anweisen/DyCloud/modules/proxy/src/main/resources/module.json
{
	"name": "Cloud-Proxy",
	"author": "anweisen",
	"version": "1.0",
	"main": "net.anweisen.cloud.modules.proxy.CloudProxyModule",
	"website": "https://github.com/anweisen/DyCloud",
	"description": "Runtime module to enable to use of proxy systems & configs",
	"environment": "MASTER",
	"copy": "PROXY"
}

=== anweisen/DyCloud/modules/perms/src/main/resources/module.json
{
	"name": "Cloud-Perms",
	"author": "anweisen",
	"version": "1.0",
	"main": "net.anweisen.cloud.modules.perms.CloudPermsModule",
	"website": "https://github.com/anweisen/DyCloud",
	"description": "Runtime module to enable to use of an integrated permission system",
	"environment": "MASTER",
	"copy": "ALL"
}

=== anweisen/DyCloud/modules/chattab/src/main/resources/module.json
{
	"name": "Cloud-ChatTab",
	"author": "anweisen",
	"version": "1.0",
	"main": "net.anweisen.cloud.modules.chattab.CloudChatTabModule",
	"website": "https://github.com/anweisen/MinecraftCloud",
	"description": "Runtime module to enable the use of chat formatting & name tags",
	"environment": "MASTER",
	"copy": "SERVER"
}
